# Generated by Django 3.2.5 on 2021-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210715_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='show_slider',
            field=models.BooleanField(default=False, verbose_name='show in slider'),
        ),
        migrations.AddField(
            model_name='item',
            name='files',
            field=models.ManyToManyField(to='shop.FeedFile'),
        ),
    ]
