# Generated by Django 3.2.5 on 2021-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_comments_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='detail',
            field=models.ManyToManyField(blank=True, null=True, to='shop.ItemDetails'),
        ),
    ]
