# Generated by Django 3.2.5 on 2021-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210720_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='show_slider',
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
